// GENERATED BY textFileToGoConst
// GitHub:     github.com/logrusorgru/textFileToGoConst
// input file: lua/add_head.lua
// generated:  Thu May 31 18:46:28 +03 2018

package redis

const addHeadLua = `--
-- add_head.lua
--

-- in:  feed, head
-- out: has_feed

local feed = 'idx:feed:' .. ARGV[1];
local head = ARGV[2];

local has_feed = redis.call('EXISTS', feed);

if has_feed == 1 then
	redis.call('HSET', feed, head, 1);
end

return has_feed;
`
